#!/usr/bin/env python3
"""analyze_song.py: the song's beat map and sung-word timestamps.

    python analyze_song.py assets/song.mp3 [--out=src/beats.js] [--var=BEATS] [--shift=0]
                           [--words=tools/words.json] [--model=small.en] [--lang=en] [--prompt=lyrics.txt]

Writes
  src/beats.js       const BEATS = [...]: one time per beat, smoothed, so pulse() and beat-timed hits lock to the real
                     track even where the tempo drifts. Beats 0, 4, 8, ... are treated as downbeats: if the first
                     detected beat isn't a downbeat, re-run with --shift=1..3 (drops that many leading beats).
  tools/words.json   [[start, end, word], ...] from Whisper word timestamps (skipped with --no-words). align_lyrics.py
                     matches these to the lyrics.
It prints what to put in src/config.js (duration, bpm, offset).

Needs ffmpeg/ffprobe on PATH and: pip install librosa faster-whisper
Whisper notes:
  - small.en is a good default for English; use --model=small (or medium) with --lang=xx for other languages.
  - --prompt=lyrics.txt feeds the lyrics as Whisper's initial prompt. It can help with names and invented words, but
    it biases the transcript toward the prompt (it may "hear" lyrics that aren't sung there). Run without it first;
    if you use it, compare the two runs before trusting it.
"""
import json, os, subprocess, sys, tempfile

import numpy as np
import librosa

if len(sys.argv) < 2 or sys.argv[1].startswith('--'):
    print(__doc__); sys.exit(1)
src = sys.argv[1]
opt = dict(a[2:].split('=', 1) for a in sys.argv[2:] if a.startswith('--') and '=' in a)
flags = {a[2:] for a in sys.argv[2:] if a.startswith('--') and '=' not in a}
OUT, VAR, SHIFT = opt.get('out', 'src/beats.js'), opt.get('var', 'BEATS'), int(opt.get('shift', 0))
WORDS = opt.get('words', 'tools/words.json')

dur = float(subprocess.run(['ffprobe', '-v', 'error', '-show_entries', 'format=duration', '-of', 'csv=p=0', src],
                           capture_output=True, text=True, check=True).stdout.strip())
wav = os.path.join(tempfile.mkdtemp(), 'song.wav')
subprocess.run(['ffmpeg', '-v', 'error', '-y', '-i', src, '-map', '0:a:0', '-ac', '1', '-ar', '22050', wav], check=True)

# ---- beats ----
y, sr = librosa.load(wav, sr=22050)
oenv = librosa.onset.onset_strength(y=y, sr=sr, hop_length=512)
tempo, bt = librosa.beat.beat_track(onset_envelope=oenv, sr=sr, hop_length=512, units='time')
if len(bt) < 8:
    sys.exit('too few beats detected: is there a steady pulse? Set bpm/offset in config.js by hand and skip beats.js.')
period = float(np.median(np.diff(bt)))
idx = np.round((bt - bt[0]) / period).astype(int)
# one time per beat index (average duplicates), fill gaps by interpolation
n = idx.max() + 1
times = np.full(n, np.nan)
for i in range(n):
    m = idx == i
    if m.any(): times[i] = bt[m].mean()
ok = ~np.isnan(times)
times = np.interp(np.arange(n), np.arange(n)[ok], times[ok])
# smooth: residual from a straight grid, median over 5 beats then mean over 9, so single-beat glitches vanish
k = np.arange(n); p = np.polyfit(k, times, 1); res = times - np.polyval(p, k)
med = np.array([np.median(res[max(0, i - 2):i + 3]) for i in range(n)])
sm = np.convolve(np.pad(med, 4, mode='edge'), np.ones(9) / 9, mode='valid')
beats = (np.polyval(p, k) + sm)[SHIFT:]
bpm = 60 / p[0]
os.makedirs(os.path.dirname(OUT) or '.', exist_ok=True)
with open(OUT, 'w') as f:
    f.write(f'// {os.path.basename(OUT)}: generated by analyze_song.py from {src}. Beat n is at {VAR}[n] seconds;\n')
    f.write(f'// beats 0, 4, 8, ... are downbeats. Tempo ~{bpm:.2f} BPM.\n')
    f.write(f'const {VAR} = [' + ','.join(f'{b:.3f}' for b in beats) + '];\n')
print(f'{len(beats)} beats, {bpm:.2f} BPM, first beat {beats[0]:.3f}s → {OUT}')
# double/half-time check: librosa often locks onto half or double the felt tempo
if bpm > 160 or bpm < 70:
    print(f'  note: {bpm:.0f} BPM may be double or half the felt tempo; check a strip of a pulse() hit against the audio')

# ---- loudness sections (a rough map of where the song gets bigger: verses vs choruses) ----
rms = librosa.feature.rms(y=y, hop_length=2048)[0]; rt = librosa.frames_to_time(np.arange(len(rms)), sr=sr, hop_length=2048)
bar = 4 * period; nb = int(dur // bar)
lv = [float(rms[(rt >= i * bar) & (rt < (i + 1) * bar)].mean()) if ((rt >= i * bar) & (rt < (i + 1) * bar)).any() else 0 for i in range(nb)]
if lv:
    q = np.percentile(lv, [33, 66])
    line = ''.join('▁' if v < q[0] else '▄' if v < q[1] else '█' for v in lv)
    print(f'loudness per bar ({bar:.2f}s each; ▁ quiet ▄ mid █ loud):')
    for i in range(0, len(line), 32): print(f'  {i * bar:7.1f}s  {line[i:i + 32]}')

print('\nsrc/config.js:')
print(f"  duration: {dur:.2f}, bpm: {round(bpm)}, offset: {beats[0]:.3f}, audio: '{src}'")

# ---- words ----
if 'no-words' in flags:
    sys.exit(0)
from faster_whisper import WhisperModel
model = opt.get('model', 'small.en')
kw = dict(word_timestamps=True, beam_size=5, vad_filter=False)
if opt.get('lang'): kw['language'] = opt['lang']
if opt.get('prompt'): kw['initial_prompt'] = ' '.join(l.strip() for l in open(opt['prompt'], encoding='utf8') if l.strip() and not l.strip().startswith('['))[:800]
print(f'\nWhisper {model}: transcribing (a few minutes on CPU)…')
m = WhisperModel(model, device='cpu', compute_type='int8')
segs, _ = m.transcribe(wav, **kw)
words = [[round(w.start, 2), round(w.end, 2), w.word.strip()] for s in segs for w in (s.words or [])]
os.makedirs(os.path.dirname(WORDS) or '.', exist_ok=True)
json.dump(words, open(WORDS, 'w'))
print(f'{len(words)} words → {WORDS}')
